{% set name = "tonic" %}
{% set version = "1.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: e43ffdb205a33efbf95357e996040ea5b0d40b1c4348b535f35a8c4142ed6e8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pbr
  run:
    - numpy
    - python >=3.6
    - tqdm
    - matplotlib-base
    - scipy
    - h5py
    - importrosbag
    - typing_extensions
    - librosa
    - expelliarmus
    - aedat
    - pbr
    - torchdata

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
