{% set name = "tonic" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: 4a9948d4d9cf1706b18902ca83c460bae16ae3fc53043a1ccecababe1f36886c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pbr
  run:
    - loris
    - numpy
    - python >=3.6
    - tqdm
    - matplotlib-base
    - scipy
    - h5py
    - importrosbag
    - typing_extensions
    - librosa
    - pbr
    - expelliarmus

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
