{% set name = "tonic" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: 2ce32849dc63a1f4edda77130e6d87cb411caacc23b7dfc6cc47d48964e14452

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pbr
  run:
    - numpy
    - python >={{ python_min }}
    - tqdm
    - matplotlib-base
    - scipy
    - h5py
    - importrosbag
    - typing_extensions
    - librosa
    - expelliarmus
    - aedat
    - pbr
    - torchdata

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
