{% set name = "tonic" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tonic-{{ version }}.tar.gz
  sha256: e7ce927e4cb733b2a8dcc0561411275381944268a7321d306e7589d3e4ef0960

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - loris
    - numpy
    - python >=3.6
    - tqdm
    - matplotlib-base
    - scipy
    - h5py
    - importrosbag
    - typing_extensions

test:
  imports:
    - tonic
    - tonic.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphs/tonic
  summary: Event-based datasets and transformations based on pyTorch vision.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
